// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/pecolynx/golang-webapi-boilerplate/src/domain"
	mock "github.com/stretchr/testify/mock"

	service "github.com/pecolynx/golang-webapi-boilerplate/src/service"
)

// TicketCreatorUsecase is an autogenerated mock type for the TicketCreatorUsecase type
type TicketCreatorUsecase struct {
	mock.Mock
}

type TicketCreatorUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *TicketCreatorUsecase) EXPECT() *TicketCreatorUsecase_Expecter {
	return &TicketCreatorUsecase_Expecter{mock: &_m.Mock}
}

// AddTicket provides a mock function with given fields: ctx, operatorID, parameter
func (_m *TicketCreatorUsecase) AddTicket(ctx context.Context, operatorID domain.StandardUserID, parameter service.TicketAddParameter) (domain.TicketID, error) {
	ret := _m.Called(ctx, operatorID, parameter)

	var r0 domain.TicketID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.StandardUserID, service.TicketAddParameter) (domain.TicketID, error)); ok {
		return rf(ctx, operatorID, parameter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.StandardUserID, service.TicketAddParameter) domain.TicketID); ok {
		r0 = rf(ctx, operatorID, parameter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.TicketID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.StandardUserID, service.TicketAddParameter) error); ok {
		r1 = rf(ctx, operatorID, parameter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TicketCreatorUsecase_AddTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTicket'
type TicketCreatorUsecase_AddTicket_Call struct {
	*mock.Call
}

// AddTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - operatorID domain.StandardUserID
//   - parameter service.TicketAddParameter
func (_e *TicketCreatorUsecase_Expecter) AddTicket(ctx interface{}, operatorID interface{}, parameter interface{}) *TicketCreatorUsecase_AddTicket_Call {
	return &TicketCreatorUsecase_AddTicket_Call{Call: _e.mock.On("AddTicket", ctx, operatorID, parameter)}
}

func (_c *TicketCreatorUsecase_AddTicket_Call) Run(run func(ctx context.Context, operatorID domain.StandardUserID, parameter service.TicketAddParameter)) *TicketCreatorUsecase_AddTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.StandardUserID), args[2].(service.TicketAddParameter))
	})
	return _c
}

func (_c *TicketCreatorUsecase_AddTicket_Call) Return(_a0 domain.TicketID, _a1 error) *TicketCreatorUsecase_AddTicket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TicketCreatorUsecase_AddTicket_Call) RunAndReturn(run func(context.Context, domain.StandardUserID, service.TicketAddParameter) (domain.TicketID, error)) *TicketCreatorUsecase_AddTicket_Call {
	_c.Call.Return(run)
	return _c
}

// FindTickets provides a mock function with given fields: ctx, operatorID, parameter
func (_m *TicketCreatorUsecase) FindTickets(ctx context.Context, operatorID domain.StandardUserID, parameter service.TicketSearchCondition) (service.TicketSearchResult, error) {
	ret := _m.Called(ctx, operatorID, parameter)

	var r0 service.TicketSearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.StandardUserID, service.TicketSearchCondition) (service.TicketSearchResult, error)); ok {
		return rf(ctx, operatorID, parameter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.StandardUserID, service.TicketSearchCondition) service.TicketSearchResult); ok {
		r0 = rf(ctx, operatorID, parameter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.TicketSearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.StandardUserID, service.TicketSearchCondition) error); ok {
		r1 = rf(ctx, operatorID, parameter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TicketCreatorUsecase_FindTickets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTickets'
type TicketCreatorUsecase_FindTickets_Call struct {
	*mock.Call
}

// FindTickets is a helper method to define mock.On call
//   - ctx context.Context
//   - operatorID domain.StandardUserID
//   - parameter service.TicketSearchCondition
func (_e *TicketCreatorUsecase_Expecter) FindTickets(ctx interface{}, operatorID interface{}, parameter interface{}) *TicketCreatorUsecase_FindTickets_Call {
	return &TicketCreatorUsecase_FindTickets_Call{Call: _e.mock.On("FindTickets", ctx, operatorID, parameter)}
}

func (_c *TicketCreatorUsecase_FindTickets_Call) Run(run func(ctx context.Context, operatorID domain.StandardUserID, parameter service.TicketSearchCondition)) *TicketCreatorUsecase_FindTickets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.StandardUserID), args[2].(service.TicketSearchCondition))
	})
	return _c
}

func (_c *TicketCreatorUsecase_FindTickets_Call) Return(_a0 service.TicketSearchResult, _a1 error) *TicketCreatorUsecase_FindTickets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TicketCreatorUsecase_FindTickets_Call) RunAndReturn(run func(context.Context, domain.StandardUserID, service.TicketSearchCondition) (service.TicketSearchResult, error)) *TicketCreatorUsecase_FindTickets_Call {
	_c.Call.Return(run)
	return _c
}

// NewTicketCreatorUsecase creates a new instance of TicketCreatorUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicketCreatorUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketCreatorUsecase {
	mock := &TicketCreatorUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
