---
with-expecter: true

mockname: "{{.InterfaceName}}"
outpkg: mocks
filename: "{{.MockName}}.go"
packages:
  github.com/pecolynx/golang-webapi-boilerplate/src/domain:
    config:
      # inpackage: True
    #   keeptree: False
      dir: src/domain/mocks
    interfaces:
      AppUserModel:
    #   BambooRequestProducer:
    #   BambooRequestConsumer:
    #   BambooResultSubscriber:
    #   BambooResultPublisher:
    #   BambooHeartbeatPublisher:
    #   BambooWorker:
    #   SubscribeFunc:
    #   CloseSubscribeConnectionFunc:
  github.com/pecolynx/golang-webapi-boilerplate/src/service:
    config:
      dir: src/service/mocks
    interfaces:
      TransactionManager:
      AppUserRepository:
      TicketRepository:
      RepositoryFactory:
      TicketCreator:
  github.com/pecolynx/golang-webapi-boilerplate/src/usecase:
    config:
      dir: src/usecase/mocks
    interfaces:
      TicketCreatorUsecase:
