// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/pecolynx/golang-webapi-boilerplate/src/domain"
	mock "github.com/stretchr/testify/mock"

	service "github.com/pecolynx/golang-webapi-boilerplate/src/service"
)

// AppUserRepository is an autogenerated mock type for the AppUserRepository type
type AppUserRepository struct {
	mock.Mock
}

type AppUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AppUserRepository) EXPECT() *AppUserRepository_Expecter {
	return &AppUserRepository_Expecter{mock: &_m.Mock}
}

// FindTicketCreatorByID provides a mock function with given fields: ctx, standardUserID
func (_m *AppUserRepository) FindTicketCreatorByID(ctx context.Context, standardUserID domain.StandardUserID) (service.TicketCreator, error) {
	ret := _m.Called(ctx, standardUserID)

	var r0 service.TicketCreator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.StandardUserID) (service.TicketCreator, error)); ok {
		return rf(ctx, standardUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.StandardUserID) service.TicketCreator); ok {
		r0 = rf(ctx, standardUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.TicketCreator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.StandardUserID) error); ok {
		r1 = rf(ctx, standardUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AppUserRepository_FindTicketCreatorByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTicketCreatorByID'
type AppUserRepository_FindTicketCreatorByID_Call struct {
	*mock.Call
}

// FindTicketCreatorByID is a helper method to define mock.On call
//   - ctx context.Context
//   - standardUserID domain.StandardUserID
func (_e *AppUserRepository_Expecter) FindTicketCreatorByID(ctx interface{}, standardUserID interface{}) *AppUserRepository_FindTicketCreatorByID_Call {
	return &AppUserRepository_FindTicketCreatorByID_Call{Call: _e.mock.On("FindTicketCreatorByID", ctx, standardUserID)}
}

func (_c *AppUserRepository_FindTicketCreatorByID_Call) Run(run func(ctx context.Context, standardUserID domain.StandardUserID)) *AppUserRepository_FindTicketCreatorByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.StandardUserID))
	})
	return _c
}

func (_c *AppUserRepository_FindTicketCreatorByID_Call) Return(_a0 service.TicketCreator, _a1 error) *AppUserRepository_FindTicketCreatorByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AppUserRepository_FindTicketCreatorByID_Call) RunAndReturn(run func(context.Context, domain.StandardUserID) (service.TicketCreator, error)) *AppUserRepository_FindTicketCreatorByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewAppUserRepository creates a new instance of AppUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppUserRepository {
	mock := &AppUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
