// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/pecolynx/golang-webapi-boilerplate/src/service"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryFactory is an autogenerated mock type for the RepositoryFactory type
type RepositoryFactory struct {
	mock.Mock
}

type RepositoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryFactory) EXPECT() *RepositoryFactory_Expecter {
	return &RepositoryFactory_Expecter{mock: &_m.Mock}
}

// NewAppUserRepository provides a mock function with given fields: ctx
func (_m *RepositoryFactory) NewAppUserRepository(ctx context.Context) service.AppUserRepository {
	ret := _m.Called(ctx)

	var r0 service.AppUserRepository
	if rf, ok := ret.Get(0).(func(context.Context) service.AppUserRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.AppUserRepository)
		}
	}

	return r0
}

// RepositoryFactory_NewAppUserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewAppUserRepository'
type RepositoryFactory_NewAppUserRepository_Call struct {
	*mock.Call
}

// NewAppUserRepository is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RepositoryFactory_Expecter) NewAppUserRepository(ctx interface{}) *RepositoryFactory_NewAppUserRepository_Call {
	return &RepositoryFactory_NewAppUserRepository_Call{Call: _e.mock.On("NewAppUserRepository", ctx)}
}

func (_c *RepositoryFactory_NewAppUserRepository_Call) Run(run func(ctx context.Context)) *RepositoryFactory_NewAppUserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RepositoryFactory_NewAppUserRepository_Call) Return(_a0 service.AppUserRepository) *RepositoryFactory_NewAppUserRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryFactory_NewAppUserRepository_Call) RunAndReturn(run func(context.Context) service.AppUserRepository) *RepositoryFactory_NewAppUserRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewRBACRepository provides a mock function with given fields: ctx
func (_m *RepositoryFactory) NewRBACRepository(ctx context.Context) service.RBACRepository {
	ret := _m.Called(ctx)

	var r0 service.RBACRepository
	if rf, ok := ret.Get(0).(func(context.Context) service.RBACRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.RBACRepository)
		}
	}

	return r0
}

// RepositoryFactory_NewRBACRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRBACRepository'
type RepositoryFactory_NewRBACRepository_Call struct {
	*mock.Call
}

// NewRBACRepository is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RepositoryFactory_Expecter) NewRBACRepository(ctx interface{}) *RepositoryFactory_NewRBACRepository_Call {
	return &RepositoryFactory_NewRBACRepository_Call{Call: _e.mock.On("NewRBACRepository", ctx)}
}

func (_c *RepositoryFactory_NewRBACRepository_Call) Run(run func(ctx context.Context)) *RepositoryFactory_NewRBACRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RepositoryFactory_NewRBACRepository_Call) Return(_a0 service.RBACRepository) *RepositoryFactory_NewRBACRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryFactory_NewRBACRepository_Call) RunAndReturn(run func(context.Context) service.RBACRepository) *RepositoryFactory_NewRBACRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewTicketRepository provides a mock function with given fields: ctx
func (_m *RepositoryFactory) NewTicketRepository(ctx context.Context) service.TicketRepository {
	ret := _m.Called(ctx)

	var r0 service.TicketRepository
	if rf, ok := ret.Get(0).(func(context.Context) service.TicketRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.TicketRepository)
		}
	}

	return r0
}

// RepositoryFactory_NewTicketRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTicketRepository'
type RepositoryFactory_NewTicketRepository_Call struct {
	*mock.Call
}

// NewTicketRepository is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RepositoryFactory_Expecter) NewTicketRepository(ctx interface{}) *RepositoryFactory_NewTicketRepository_Call {
	return &RepositoryFactory_NewTicketRepository_Call{Call: _e.mock.On("NewTicketRepository", ctx)}
}

func (_c *RepositoryFactory_NewTicketRepository_Call) Run(run func(ctx context.Context)) *RepositoryFactory_NewTicketRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RepositoryFactory_NewTicketRepository_Call) Return(_a0 service.TicketRepository) *RepositoryFactory_NewTicketRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryFactory_NewTicketRepository_Call) RunAndReturn(run func(context.Context) service.TicketRepository) *RepositoryFactory_NewTicketRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryFactory creates a new instance of RepositoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryFactory {
	mock := &RepositoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
