// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/pecolynx/golang-webapi-boilerplate/src/domain"
	mock "github.com/stretchr/testify/mock"

	service "github.com/pecolynx/golang-webapi-boilerplate/src/service"

	time "time"
)

// TicketCreator is an autogenerated mock type for the TicketCreator type
type TicketCreator struct {
	mock.Mock
}

type TicketCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *TicketCreator) EXPECT() *TicketCreator_Expecter {
	return &TicketCreator_Expecter{mock: &_m.Mock}
}

// AddTicket provides a mock function with given fields: ctx, param
func (_m *TicketCreator) AddTicket(ctx context.Context, param service.TicketAddParameter) (domain.TicketID, error) {
	ret := _m.Called(ctx, param)

	var r0 domain.TicketID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.TicketAddParameter) (domain.TicketID, error)); ok {
		return rf(ctx, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.TicketAddParameter) domain.TicketID); ok {
		r0 = rf(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.TicketID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.TicketAddParameter) error); ok {
		r1 = rf(ctx, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TicketCreator_AddTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTicket'
type TicketCreator_AddTicket_Call struct {
	*mock.Call
}

// AddTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - param service.TicketAddParameter
func (_e *TicketCreator_Expecter) AddTicket(ctx interface{}, param interface{}) *TicketCreator_AddTicket_Call {
	return &TicketCreator_AddTicket_Call{Call: _e.mock.On("AddTicket", ctx, param)}
}

func (_c *TicketCreator_AddTicket_Call) Run(run func(ctx context.Context, param service.TicketAddParameter)) *TicketCreator_AddTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.TicketAddParameter))
	})
	return _c
}

func (_c *TicketCreator_AddTicket_Call) Return(_a0 domain.TicketID, _a1 error) *TicketCreator_AddTicket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TicketCreator_AddTicket_Call) RunAndReturn(run func(context.Context, service.TicketAddParameter) (domain.TicketID, error)) *TicketCreator_AddTicket_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppUserID provides a mock function with given fields:
func (_m *TicketCreator) GetAppUserID() domain.AppUserID {
	ret := _m.Called()

	var r0 domain.AppUserID
	if rf, ok := ret.Get(0).(func() domain.AppUserID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.AppUserID)
		}
	}

	return r0
}

// TicketCreator_GetAppUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppUserID'
type TicketCreator_GetAppUserID_Call struct {
	*mock.Call
}

// GetAppUserID is a helper method to define mock.On call
func (_e *TicketCreator_Expecter) GetAppUserID() *TicketCreator_GetAppUserID_Call {
	return &TicketCreator_GetAppUserID_Call{Call: _e.mock.On("GetAppUserID")}
}

func (_c *TicketCreator_GetAppUserID_Call) Run(run func()) *TicketCreator_GetAppUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TicketCreator_GetAppUserID_Call) Return(_a0 domain.AppUserID) *TicketCreator_GetAppUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketCreator_GetAppUserID_Call) RunAndReturn(run func() domain.AppUserID) *TicketCreator_GetAppUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCreatedAt provides a mock function with given fields:
func (_m *TicketCreator) GetCreatedAt() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// TicketCreator_GetCreatedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreatedAt'
type TicketCreator_GetCreatedAt_Call struct {
	*mock.Call
}

// GetCreatedAt is a helper method to define mock.On call
func (_e *TicketCreator_Expecter) GetCreatedAt() *TicketCreator_GetCreatedAt_Call {
	return &TicketCreator_GetCreatedAt_Call{Call: _e.mock.On("GetCreatedAt")}
}

func (_c *TicketCreator_GetCreatedAt_Call) Run(run func()) *TicketCreator_GetCreatedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TicketCreator_GetCreatedAt_Call) Return(_a0 time.Time) *TicketCreator_GetCreatedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketCreator_GetCreatedAt_Call) RunAndReturn(run func() time.Time) *TicketCreator_GetCreatedAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetCreatedBy provides a mock function with given fields:
func (_m *TicketCreator) GetCreatedBy() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// TicketCreator_GetCreatedBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreatedBy'
type TicketCreator_GetCreatedBy_Call struct {
	*mock.Call
}

// GetCreatedBy is a helper method to define mock.On call
func (_e *TicketCreator_Expecter) GetCreatedBy() *TicketCreator_GetCreatedBy_Call {
	return &TicketCreator_GetCreatedBy_Call{Call: _e.mock.On("GetCreatedBy")}
}

func (_c *TicketCreator_GetCreatedBy_Call) Run(run func()) *TicketCreator_GetCreatedBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TicketCreator_GetCreatedBy_Call) Return(_a0 int) *TicketCreator_GetCreatedBy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketCreator_GetCreatedBy_Call) RunAndReturn(run func() int) *TicketCreator_GetCreatedBy_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoginID provides a mock function with given fields:
func (_m *TicketCreator) GetLoginID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TicketCreator_GetLoginID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoginID'
type TicketCreator_GetLoginID_Call struct {
	*mock.Call
}

// GetLoginID is a helper method to define mock.On call
func (_e *TicketCreator_Expecter) GetLoginID() *TicketCreator_GetLoginID_Call {
	return &TicketCreator_GetLoginID_Call{Call: _e.mock.On("GetLoginID")}
}

func (_c *TicketCreator_GetLoginID_Call) Run(run func()) *TicketCreator_GetLoginID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TicketCreator_GetLoginID_Call) Return(_a0 string) *TicketCreator_GetLoginID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketCreator_GetLoginID_Call) RunAndReturn(run func() string) *TicketCreator_GetLoginID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpdatedAt provides a mock function with given fields:
func (_m *TicketCreator) GetUpdatedAt() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// TicketCreator_GetUpdatedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdatedAt'
type TicketCreator_GetUpdatedAt_Call struct {
	*mock.Call
}

// GetUpdatedAt is a helper method to define mock.On call
func (_e *TicketCreator_Expecter) GetUpdatedAt() *TicketCreator_GetUpdatedAt_Call {
	return &TicketCreator_GetUpdatedAt_Call{Call: _e.mock.On("GetUpdatedAt")}
}

func (_c *TicketCreator_GetUpdatedAt_Call) Run(run func()) *TicketCreator_GetUpdatedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TicketCreator_GetUpdatedAt_Call) Return(_a0 time.Time) *TicketCreator_GetUpdatedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketCreator_GetUpdatedAt_Call) RunAndReturn(run func() time.Time) *TicketCreator_GetUpdatedAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpdatedBy provides a mock function with given fields:
func (_m *TicketCreator) GetUpdatedBy() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// TicketCreator_GetUpdatedBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdatedBy'
type TicketCreator_GetUpdatedBy_Call struct {
	*mock.Call
}

// GetUpdatedBy is a helper method to define mock.On call
func (_e *TicketCreator_Expecter) GetUpdatedBy() *TicketCreator_GetUpdatedBy_Call {
	return &TicketCreator_GetUpdatedBy_Call{Call: _e.mock.On("GetUpdatedBy")}
}

func (_c *TicketCreator_GetUpdatedBy_Call) Run(run func()) *TicketCreator_GetUpdatedBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TicketCreator_GetUpdatedBy_Call) Return(_a0 int) *TicketCreator_GetUpdatedBy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketCreator_GetUpdatedBy_Call) RunAndReturn(run func() int) *TicketCreator_GetUpdatedBy_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsername provides a mock function with given fields:
func (_m *TicketCreator) GetUsername() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TicketCreator_GetUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsername'
type TicketCreator_GetUsername_Call struct {
	*mock.Call
}

// GetUsername is a helper method to define mock.On call
func (_e *TicketCreator_Expecter) GetUsername() *TicketCreator_GetUsername_Call {
	return &TicketCreator_GetUsername_Call{Call: _e.mock.On("GetUsername")}
}

func (_c *TicketCreator_GetUsername_Call) Run(run func()) *TicketCreator_GetUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TicketCreator_GetUsername_Call) Return(_a0 string) *TicketCreator_GetUsername_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketCreator_GetUsername_Call) RunAndReturn(run func() string) *TicketCreator_GetUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with given fields:
func (_m *TicketCreator) GetVersion() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// TicketCreator_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type TicketCreator_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
func (_e *TicketCreator_Expecter) GetVersion() *TicketCreator_GetVersion_Call {
	return &TicketCreator_GetVersion_Call{Call: _e.mock.On("GetVersion")}
}

func (_c *TicketCreator_GetVersion_Call) Run(run func()) *TicketCreator_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TicketCreator_GetVersion_Call) Return(_a0 int) *TicketCreator_GetVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketCreator_GetVersion_Call) RunAndReturn(run func() int) *TicketCreator_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewTicketCreator creates a new instance of TicketCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicketCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketCreator {
	mock := &TicketCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
