// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/pecolynx/golang-webapi-boilerplate/src/domain"
	mock "github.com/stretchr/testify/mock"

	service "github.com/pecolynx/golang-webapi-boilerplate/src/service"
)

// TicketRepository is an autogenerated mock type for the TicketRepository type
type TicketRepository struct {
	mock.Mock
}

type TicketRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TicketRepository) EXPECT() *TicketRepository_Expecter {
	return &TicketRepository_Expecter{mock: &_m.Mock}
}

// AddTicket provides a mock function with given fields: ctx, operator, param
func (_m *TicketRepository) AddTicket(ctx context.Context, operator service.TicketCreator, param service.TicketAddParameter) (domain.TicketID, error) {
	ret := _m.Called(ctx, operator, param)

	var r0 domain.TicketID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.TicketCreator, service.TicketAddParameter) (domain.TicketID, error)); ok {
		return rf(ctx, operator, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.TicketCreator, service.TicketAddParameter) domain.TicketID); ok {
		r0 = rf(ctx, operator, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.TicketID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.TicketCreator, service.TicketAddParameter) error); ok {
		r1 = rf(ctx, operator, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TicketRepository_AddTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTicket'
type TicketRepository_AddTicket_Call struct {
	*mock.Call
}

// AddTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - operator service.TicketCreator
//   - param service.TicketAddParameter
func (_e *TicketRepository_Expecter) AddTicket(ctx interface{}, operator interface{}, param interface{}) *TicketRepository_AddTicket_Call {
	return &TicketRepository_AddTicket_Call{Call: _e.mock.On("AddTicket", ctx, operator, param)}
}

func (_c *TicketRepository_AddTicket_Call) Run(run func(ctx context.Context, operator service.TicketCreator, param service.TicketAddParameter)) *TicketRepository_AddTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.TicketCreator), args[2].(service.TicketAddParameter))
	})
	return _c
}

func (_c *TicketRepository_AddTicket_Call) Return(_a0 domain.TicketID, _a1 error) *TicketRepository_AddTicket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TicketRepository_AddTicket_Call) RunAndReturn(run func(context.Context, service.TicketCreator, service.TicketAddParameter) (domain.TicketID, error)) *TicketRepository_AddTicket_Call {
	_c.Call.Return(run)
	return _c
}

// NewTicketRepository creates a new instance of TicketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketRepository {
	mock := &TicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
