// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/pecolynx/golang-webapi-boilerplate/src/service"
	mock "github.com/stretchr/testify/mock"
)

// TransactionManager is an autogenerated mock type for the TransactionManager type
type TransactionManager struct {
	mock.Mock
}

type TransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionManager) EXPECT() *TransactionManager_Expecter {
	return &TransactionManager_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: ctx, fn
func (_m *TransactionManager) Do(ctx context.Context, fn func(service.RepositoryFactory) error) error {
	ret := _m.Called(ctx, fn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(service.RepositoryFactory) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionManager_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type TransactionManager_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(service.RepositoryFactory) error
func (_e *TransactionManager_Expecter) Do(ctx interface{}, fn interface{}) *TransactionManager_Do_Call {
	return &TransactionManager_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *TransactionManager_Do_Call) Run(run func(ctx context.Context, fn func(service.RepositoryFactory) error)) *TransactionManager_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(service.RepositoryFactory) error))
	})
	return _c
}

func (_c *TransactionManager_Do_Call) Return(_a0 error) *TransactionManager_Do_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionManager_Do_Call) RunAndReturn(run func(context.Context, func(service.RepositoryFactory) error) error) *TransactionManager_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionManager creates a new instance of TransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionManager {
	mock := &TransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
