// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/pecolynx/golang-webapi-boilerplate/src/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AppUserModel is an autogenerated mock type for the AppUserModel type
type AppUserModel struct {
	mock.Mock
}

type AppUserModel_Expecter struct {
	mock *mock.Mock
}

func (_m *AppUserModel) EXPECT() *AppUserModel_Expecter {
	return &AppUserModel_Expecter{mock: &_m.Mock}
}

// GetAppUserID provides a mock function with given fields:
func (_m *AppUserModel) GetAppUserID() domain.AppUserID {
	ret := _m.Called()

	var r0 domain.AppUserID
	if rf, ok := ret.Get(0).(func() domain.AppUserID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.AppUserID)
		}
	}

	return r0
}

// AppUserModel_GetAppUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppUserID'
type AppUserModel_GetAppUserID_Call struct {
	*mock.Call
}

// GetAppUserID is a helper method to define mock.On call
func (_e *AppUserModel_Expecter) GetAppUserID() *AppUserModel_GetAppUserID_Call {
	return &AppUserModel_GetAppUserID_Call{Call: _e.mock.On("GetAppUserID")}
}

func (_c *AppUserModel_GetAppUserID_Call) Run(run func()) *AppUserModel_GetAppUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppUserModel_GetAppUserID_Call) Return(_a0 domain.AppUserID) *AppUserModel_GetAppUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppUserModel_GetAppUserID_Call) RunAndReturn(run func() domain.AppUserID) *AppUserModel_GetAppUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCreatedAt provides a mock function with given fields:
func (_m *AppUserModel) GetCreatedAt() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// AppUserModel_GetCreatedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreatedAt'
type AppUserModel_GetCreatedAt_Call struct {
	*mock.Call
}

// GetCreatedAt is a helper method to define mock.On call
func (_e *AppUserModel_Expecter) GetCreatedAt() *AppUserModel_GetCreatedAt_Call {
	return &AppUserModel_GetCreatedAt_Call{Call: _e.mock.On("GetCreatedAt")}
}

func (_c *AppUserModel_GetCreatedAt_Call) Run(run func()) *AppUserModel_GetCreatedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppUserModel_GetCreatedAt_Call) Return(_a0 time.Time) *AppUserModel_GetCreatedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppUserModel_GetCreatedAt_Call) RunAndReturn(run func() time.Time) *AppUserModel_GetCreatedAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetCreatedBy provides a mock function with given fields:
func (_m *AppUserModel) GetCreatedBy() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// AppUserModel_GetCreatedBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreatedBy'
type AppUserModel_GetCreatedBy_Call struct {
	*mock.Call
}

// GetCreatedBy is a helper method to define mock.On call
func (_e *AppUserModel_Expecter) GetCreatedBy() *AppUserModel_GetCreatedBy_Call {
	return &AppUserModel_GetCreatedBy_Call{Call: _e.mock.On("GetCreatedBy")}
}

func (_c *AppUserModel_GetCreatedBy_Call) Run(run func()) *AppUserModel_GetCreatedBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppUserModel_GetCreatedBy_Call) Return(_a0 int) *AppUserModel_GetCreatedBy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppUserModel_GetCreatedBy_Call) RunAndReturn(run func() int) *AppUserModel_GetCreatedBy_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoginID provides a mock function with given fields:
func (_m *AppUserModel) GetLoginID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AppUserModel_GetLoginID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoginID'
type AppUserModel_GetLoginID_Call struct {
	*mock.Call
}

// GetLoginID is a helper method to define mock.On call
func (_e *AppUserModel_Expecter) GetLoginID() *AppUserModel_GetLoginID_Call {
	return &AppUserModel_GetLoginID_Call{Call: _e.mock.On("GetLoginID")}
}

func (_c *AppUserModel_GetLoginID_Call) Run(run func()) *AppUserModel_GetLoginID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppUserModel_GetLoginID_Call) Return(_a0 string) *AppUserModel_GetLoginID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppUserModel_GetLoginID_Call) RunAndReturn(run func() string) *AppUserModel_GetLoginID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpdatedAt provides a mock function with given fields:
func (_m *AppUserModel) GetUpdatedAt() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// AppUserModel_GetUpdatedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdatedAt'
type AppUserModel_GetUpdatedAt_Call struct {
	*mock.Call
}

// GetUpdatedAt is a helper method to define mock.On call
func (_e *AppUserModel_Expecter) GetUpdatedAt() *AppUserModel_GetUpdatedAt_Call {
	return &AppUserModel_GetUpdatedAt_Call{Call: _e.mock.On("GetUpdatedAt")}
}

func (_c *AppUserModel_GetUpdatedAt_Call) Run(run func()) *AppUserModel_GetUpdatedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppUserModel_GetUpdatedAt_Call) Return(_a0 time.Time) *AppUserModel_GetUpdatedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppUserModel_GetUpdatedAt_Call) RunAndReturn(run func() time.Time) *AppUserModel_GetUpdatedAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpdatedBy provides a mock function with given fields:
func (_m *AppUserModel) GetUpdatedBy() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// AppUserModel_GetUpdatedBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdatedBy'
type AppUserModel_GetUpdatedBy_Call struct {
	*mock.Call
}

// GetUpdatedBy is a helper method to define mock.On call
func (_e *AppUserModel_Expecter) GetUpdatedBy() *AppUserModel_GetUpdatedBy_Call {
	return &AppUserModel_GetUpdatedBy_Call{Call: _e.mock.On("GetUpdatedBy")}
}

func (_c *AppUserModel_GetUpdatedBy_Call) Run(run func()) *AppUserModel_GetUpdatedBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppUserModel_GetUpdatedBy_Call) Return(_a0 int) *AppUserModel_GetUpdatedBy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppUserModel_GetUpdatedBy_Call) RunAndReturn(run func() int) *AppUserModel_GetUpdatedBy_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsername provides a mock function with given fields:
func (_m *AppUserModel) GetUsername() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AppUserModel_GetUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsername'
type AppUserModel_GetUsername_Call struct {
	*mock.Call
}

// GetUsername is a helper method to define mock.On call
func (_e *AppUserModel_Expecter) GetUsername() *AppUserModel_GetUsername_Call {
	return &AppUserModel_GetUsername_Call{Call: _e.mock.On("GetUsername")}
}

func (_c *AppUserModel_GetUsername_Call) Run(run func()) *AppUserModel_GetUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppUserModel_GetUsername_Call) Return(_a0 string) *AppUserModel_GetUsername_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppUserModel_GetUsername_Call) RunAndReturn(run func() string) *AppUserModel_GetUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with given fields:
func (_m *AppUserModel) GetVersion() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// AppUserModel_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type AppUserModel_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
func (_e *AppUserModel_Expecter) GetVersion() *AppUserModel_GetVersion_Call {
	return &AppUserModel_GetVersion_Call{Call: _e.mock.On("GetVersion")}
}

func (_c *AppUserModel_GetVersion_Call) Run(run func()) *AppUserModel_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppUserModel_GetVersion_Call) Return(_a0 int) *AppUserModel_GetVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppUserModel_GetVersion_Call) RunAndReturn(run func() int) *AppUserModel_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewAppUserModel creates a new instance of AppUserModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppUserModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppUserModel {
	mock := &AppUserModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
